Adds rvalue overloads for var matrices
stan-dev/stan pull request #2991
Opened 2020-12-17 22:18 UTC by SteveBronder

#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

This adds all the `rvalue()` overloads needed for `var<matrix>` and relaxes the templates on the current overloads that can handle `var<matrix>`

The only rvalue overloads needed are the for `index_multi` since we have to have a callback to propogate adjoints.

#### Intended Effect

Allow subsetting in Stan models when using `var<matrix>`

#### How to Verify

Manual tests have been added for all single index and all indices on the right hand side for matrices. Then a larger automated test is run that tests all pair combinations of indices.

#### Side Effects

#### Documentation

Docs added for each new overload and original docs for rvalue overloads updated for when they can accept either Eigen matrices or `var<matrix>` types

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Steve Bronder

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

2020-12-18 09:38 UTC, t4c1 requested changes

2020-12-18 09:38 UTC, t4c1 commented on src/stan/model/indexing/rvalue_varmat.hpp
> +      [head = idxs.head_, x, x_ret, col_idx, name, depth]() mutable {
I dont see name or depth used in the lambda.

2020-12-19 00:38 UTC, SteveBronder commented on src/stan/model/indexing/rvalue_varmat.hpp
> + * Return the specified matrix at the specified multi index.
Yes i also went through and fixed up the docs for `idx` so it was more obvious what each one did

2020-12-19 00:38 UTC, SteveBronder commented on src/stan/model/indexing/rvalue_varmat.hpp
> +    x_ret_vals.coeffRef(i) = x.vi_->val_.coeffRef(row_idx[i]);
Went through and checked this over both

2020-12-21 08:32 UTC, t4c1 approved these changes

2020-12-21 08:33 UTC, merged

2020-12-22 10:35 UTC, rok-cesnovar commented
@SteveBronder cmdstan Windows Rtools 3.5 test is failing after this PR was merged. See https://github.com/stan-dev/cmdstan/runs/1591785707 and https://pipelines.actions.githubusercontent.com/IWD9CSoapEZ4VsVQhL3f8rgS1MWkcN50p1yldEctrAl8hmLKx1/_apis/pipelines/1/runs/286/signedlogcontent/3?urlExpires=2020-12-22T10%3A24%3A24.1063345Z&urlSigningMethod=HMACV1&urlSignature=u1xcmK7mG%2B9qOtorsydy4sWoOcopJ2cvK9duGu7NorU%3D

```cpp
--- Translating Stan model to C++ code ---
bin/stanc.exe  --o=examples/bernoulli/bernoulli.hpp examples/bernoulli/bernoulli.stan

--- Compiling, linking C++ code ---
g++ -std=c++1y -m64 -D_REENTRANT -Wall -Wno-unused-function -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-variable -Wno-sign-compare -Wno-unused-local-typedefs -Wno-int-in-bool-context -Wno-attributes -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2019_U8/include   -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.9 -I stan/lib/stan_math/lib/boost_1.72.0 -I stan/lib/stan_math/lib/sundials_5.5.0/include  -D_USE_MATH_DEFINES  -DBOOST_DISABLE_ASSERTS         -c  -x c++ -o examples/bernoulli/bernoulli.o examples/bernoulli/bernoulli.hpp
In file included from stan/src/stan/model/indexing/lvalue.hpp:8:0,
                 from stan/src/stan/model/indexing.hpp:7,
                 from stan/src/stan/model/model_header.hpp:15,
                 from examples/bernoulli/bernoulli.hpp:3:
stan/src/stan/model/indexing/rvalue_at.hpp: In function 'constexpr int stan::model::rvalue_at(int, const stan::model::index_min_max&)':
stan/src/stan/model/indexing/rvalue_at.hpp:75:1: error: body of constexpr function 'constexpr int stan::model::rvalue_at(int, const stan::model::index_min_max&)' not a return-statement
 }
 ^
```
The error message is not very helpful unfortunately.

This is not super urgent as develop tests will not fail due to this, but would still be great to address soon.

2020-12-22 20:32 UTC, SteveBronder commented
Oh yes I know how to fix this I'll put up a PR right now. I think it's because windows does not have full C++14 support so it's failing when trying to eval this

2020-12-22 20:40 UTC, SteveBronder commented
@rok-cesnovar just put this up, will fix the above

https://github.com/stan-dev/stan/pull/2993