Adds free function tests for serializer
stan-dev/stan pull request #3036
Opened 2021-04-08 17:07 UTC by SteveBronder

#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

For the refactoring of `transform_inits()` in the compiler we actually need the free functions to be in the serializer. See the discussion [here](https://github.com/stan-dev/stanc3/pull/872#issuecomment-815128608) for more info.

#### Intended Effect

Allow the serializer to perform the free'ing of constrained variables

#### How to Verify

Tests were added to do the same checks as the `deserializer`'s free tests

```bash
./runTests.py ./src/test/unit/io/serializer_test.cpp
```

#### Side Effects

#### Documentation

Documentation for each of the free functions in `serializer`

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Steve Bronder

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

2021-04-15 16:50 UTC, SteveBronder commented
@rok-cesnovar or @t4c1 do one of yinz have time to look this over?

2021-04-15 16:54 UTC, rok-cesnovar commented
I can take a look.

2021-04-16 12:03 UTC, t4c1 requested changes
Tests look good.

2021-04-21 01:36 UTC, SteveBronder commented
@t4c1 made the above fix ready for another look!

2021-04-21 06:13 UTC, t4c1 approved these changes
Looks good.

2021-04-21 06:13 UTC, merged