Feature/3247 json metric type - add field "metric_type" to metric.json file
stan-dev/stan pull request #3248
Opened 2023-12-08 21:04 UTC by mitzimorris

#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

Add field "metric_type" with values "diag_e", "dense_e", and "unit_e" to json metric file.

#### Intended Effect

Make it easier to restart sampler - always specify metric type.

#### How to Verify

Unit tests will be added to CmdStan's tests of this feature once this PR is merged.

#### Side Effects

N/A

#### Documentation

N/A
#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):   Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

2023-12-08 21:20 UTC, WardBrian requested changes
Besides testing further downstream in cmdstan, we are testing the rest of this feature in the following files:

```
src/test/unit/services/sample/hmc_nuts_unit_e_adapt_parallel_test.cpp
src/test/unit/services/sample/hmc_nuts_diag_e_adapt_parallel_match_test.cpp
src/test/unit/services/sample/hmc_nuts_dense_e_adapt_parallel_match_test.cpp
```

I think we should add the test that this is output as expected to those three files. Should be short for each of them

2023-12-08 21:20 UTC, WardBrian commented on src/stan/mcmc/hmc/base_hmc.hpp
> +    struct_writer.write("metric_type", z_.metric_type());
This is a nitpick, but could this be written out before the actual metric itself? I'm imaging a situation where you're reading this file and want to pre-allocate something for the metric to be read into, but that requires knowing the type before you start reading it

2023-12-09 18:04 UTC, mitzimorris commented
changes made; ready for re-review

2023-12-11 20:14 UTC, WardBrian approved these changes

2023-12-11 20:46 UTC, merged